spring:
  application:
    name: seguridad-vigilancia
  datasource:
    url: jdbc:mysql://localhost:3306/seguridad_vigilancia
    username: root
    password: yourpassword
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
